### ISSUE TITLE
My first script, ready for grading.

### ISSUE THREAD

**Issue by cpsaffold** [madisoncollege-it-programs/python-scripting-cpsaffold#2]

**Comment by cethenmc** [comment]
Hi, Caleb.  For this week #2 assignment #2 task, I would like you to be able to run this from the command line.  If your shbang line is in their correctly, then please go to week2 and execute the following command to modify the rights.

chmod u+x first-script.py

Then execute the file from command line.

./first-script.py

If it renders results, then...

1.     add the file to staging (git add .)
2.     commit the file to your local repo. (git commit -m "changes requested to run from command line")
3.     push to the git hub repository (git push)
4.     reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by cethenmc** [comment]
Hi, Jacob.  For Week 2, Assignment #2 (first-script.py)...

I would like you to update your script so you can run it from the command line.

Your first line should always be the following for your scripts. In this way, if you are running from the command line it will know what interpreter to use. Will you please add this line to the top of your first-script.py code?

#!/usr/bin/env python3

Recall from the videos, you may also need to issue a chmod command to modify the rights to make it executable.

chmod u+x first-script.py

After this, you can execute from the command line.

./first-script.py

Please be so kind as to resubmit it, so...
    1. modify the file in NetLab with the added line at the top.
    2. update the file to be executable.
    3. add the file to staging (git add .)
    4. commit the file to your local repo. (git commit -m "changes requested to run from command line")
    5. push to the git hub repository (git push)
    6. reply to this same issue, saying you have completed these steps

Thanks.

~Chris

**Comment by cethenmc** [comment]
Caleb - This looks good now.   Graded and closed.
