### ISSUE TITLE
String Formatting Ready to be Graded

### ISSUE THREAD

**Issue by cpsaffold** [madisoncollege-it-programs/python-scripting-cpsaffold#4]

**Comment by cethenmc** [comment]
Hi, Caleb.  I think I advised you to pull the space out between the "] [" on #12 and #13.  I was going from memory and a very small screen when you were sharing, so I apologize.  You were correct.  When I downloaded my answer key and opened the Word document on my full-size monitor, they should indeed have a single space between the square brackets.  Full credit to you!  Thanks for the effort, and please keep practicing.  ~Chris
