### ISSUE TITLE
Week 6 Flow Control Ready for grading

### ISSUE THREAD

**Issue by cpsaffold** [madisoncollege-it-programs/python-scripting-cpsaffold#7]

**Comment by cethenmc** [comment]
Hi, Caleb.  Your third door needs to do something other than if someone chose a 4.  I did see you switched other choices for door 1 and 2, but adding the third door is necessary to the assignment.

$ ./flowcontrol.py 
You enter a grimy room with three doors.Do you go through door #1, door #2, or door #3?
-> 3
You did not select a door??? Good Call

Perhaps you did it and just forgot to push it to GitHub?

**I will record 4 of 8 in the grade book, but if you fix within a week you can get full credit.**

Thanks.

Chris

**Comment by cethenmc** [comment]
Thanks for adding door 3 now.  Changed to full credit!
